# Generated by Django 4.2.10 on 2024-02-14 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_venda', models.DateField(default=datetime.datetime(2024, 2, 14, 11, 9, 27, 58765, tzinfo=datetime.timezone.utc))),
                ('forma_pagamento', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barraquinhas.produtos')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barraquinhas.vendas')),
            ],
        ),
    ]
