# Generated by Django 4.2.10 on 2024-02-16 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0002_vendas_itensvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 2, 45, 5, 85092, tzinfo=datetime.timezone.utc)),
        ),
    ]
