# Generated by Django 4.2.10 on 2024-02-16 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0003_alter_produtos_valor_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 3, 34, 3, 815700, tzinfo=datetime.timezone.utc)),
        ),
    ]
