# Generated by Django 4.2.10 on 2024-02-18 02:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barraquinhas', '0004_alter_produtos_options_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='id_vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 2, 45, 6, 130294, tzinfo=datetime.timezone.utc)),
        ),
    ]
