# Generated by Django 4.2.10 on 2024-04-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0005_vendas_id_vendedor_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 22, 30, 55, 459972, tzinfo=datetime.timezone.utc)),
        ),
    ]
