# Generated by Django 4.2.10 on 2024-04-10 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0006_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentos'), ('B', 'Bebidas'), ('J', 'Jogos'), ('D', 'Doação'), ('O', 'Outros')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 10, 58, 24, 810165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Catão de Débito'), (3, 'Cartão de Crédito'), (4, 'PIX'), (5, 'Doação')], default=1),
        ),
    ]
