# Generated by Django 4.2.10 on 2024-04-11 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0008_remove_itensvenda_ativo_vendas_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'ordering': ['-data_venda'], 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 16, 29, 42, 664628, tzinfo=datetime.timezone.utc)),
        ),
    ]
