# Generated by Django 4.2.10 on 2024-04-14 03:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barraquinhas', '0010_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.datetime(2024, 4, 14, 3, 42, 4, 868840, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
