# Generated by Django 4.2.10 on 2024-04-15 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0011_alter_vendas_data_venda_usercell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.date(2024, 4, 14)),
        ),
    ]
