# Generated by Django 4.2.10 on 2024-05-26 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0013_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.date(2024, 5, 26)),
        ),
        migrations.DeleteModel(
            name='UserCell',
        ),
    ]
