# Generated by Django 4.2.10 on 2024-06-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0015_remove_vendas_id_vendedor_alter_vendas_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
