# Generated by Django 4.2.10 on 2024-06-09 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barraquinhas', '0017_alter_vendas_data_venda_alter_vendas_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='valor_unitario',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(default=datetime.date(2024, 6, 9)),
        ),
    ]
