version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: sistema_igreja
    ports:
      - 5430:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
      
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_sistema_igreja
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data: